// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoQMgiHOGKVbwxKYUDe7kWCM3w-wsJQCs',
    appId: '1:257049264720:web:6f99135da19318364f4755',
    messagingSenderId: '257049264720',
    projectId: 'messageabdo-25b84',
    authDomain: 'messageabdo-25b84.firebaseapp.com',
    storageBucket: 'messageabdo-25b84.appspot.com',
    measurementId: 'G-L8JNDKBTH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJoJ0Uv1EwtapwACejOaY1ciXMRaQYcmY',
    appId: '1:257049264720:android:c0817d849b45ae884f4755',
    messagingSenderId: '257049264720',
    projectId: 'messageabdo-25b84',
    storageBucket: 'messageabdo-25b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Af7v9IEMjtrNr4E26NmLPWcb0WDS-r0',
    appId: '1:257049264720:ios:59aaf35e4407b2d64f4755',
    messagingSenderId: '257049264720',
    projectId: 'messageabdo-25b84',
    storageBucket: 'messageabdo-25b84.appspot.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Af7v9IEMjtrNr4E26NmLPWcb0WDS-r0',
    appId: '1:257049264720:ios:2a7a16bcd7fafd3e4f4755',
    messagingSenderId: '257049264720',
    projectId: 'messageabdo-25b84',
    storageBucket: 'messageabdo-25b84.appspot.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
